Speed up jr significantly

diff --git a/jr b/jr
--- a/jr
+++ b/jr
@@ -10,6 +10,7 @@
 #      - invalid flag if flag passed without any arguments
 #      - file is not deleted if user exits using ctrl-c
 #      - javac can just be skipped if the file being compiled has no dependencies
+#      - do not use javac twice
 
 d_flag=false # delete the compiled files if true
 h_flag=false # use of help flag - do not exit with error
@@ -90,51 +91,54 @@ remove_compiled_files() {
     fi
 }
 
+compile_test() {
+    if [[ "$1" == 'package' ]]; then
+        stderr=$(javac -d . *.java)
+    elif [[ "$1" == 'single' ]]; then
+        stderr=$(javac "${main_file}.java")
+    elif [[ "$1" == 'junit' ]]; then
+        # do not compile JUnitTests.java file
+        stderr=$(find . -maxdepth 1 -type f ! -iname 'JUnitTests.java' -iname '*.java' -exec javac -d . {} +)
+    fi
+
+    return_code="$?" # determine if the compile fails or succeeds
+
+    if [[ "$stderr" =~ "Usage" ]]; then
+        echo "$stderr" | sed -z --expression='s/javac/jr/; s:<:[:; s:>:]:' # quote $stderr to preserve spacing
+        exit 1 # should this just return the exit code instead
+    fi
+
+    return $return_code
+}
+
 # TODO - check if the file passed with jr is actually in the directory before running
 #      - check what happens when a file that takes input is cancelled (^C) mid-run
 # can the javac in the branches be replaced with javac -d . "$1" ?
 compile_files() {
     if [[ -n "$package_name" ]]; then
-        # simplify below if possible
-        # FIXME - print out stderr, if needed, without having to run javac twice
-        stderr="$(javac -d . *.java 2>&1 > /dev/null)"
-        if [[ "$stderr" =~ "Usage" ]]; then # check if there is a usage error instead of source code error
-            # below works but is there a way to speed it up?
-            echo "$stderr" | sed -z --expression='s/javac/jr/; s:<:[:; s:>:]:' # quote $stderr to preserve spacing
-            exit 1
-        fi
-
-        # could also try using extglob
-        # TODO - clean this code up
-        if [[ -f "JUnitTests.java" ]] && { [[ ! -f ".timestamp" ]] || [[ ".timestamp" -ot "${main_file}.java" ]]; }; then
-            find . -maxdepth 1 -type f ! -iname "JUnitTests.java" -iname '*java' -exec javac -d . {} +
-            java "$package_name.$main_file" 2> /dev/null && remove_compiled_files directory
-            return
-        fi
-
-        # only recompile if any of the .java files have been changed
-        # this works because java automatically recompiles when one of the component files is newer
         if [[ ! -f ".timestamp" ]] || [[ ".timestamp" -ot "${main_file}.java" ]]; then
             touch ".timestamp"
-            { javac -d . *.java && java "$package_name.$main_file" && remove_compiled_files directory; } || rm ".timestamp"
+            if [[ -f "JUnitTests.java" ]]; then
+                compile_test "junit"
+            else
+                compile_test "package"
+            fi
+        fi
+        # only do the below if compile_test does not fail
+        if (( $? != 0 )); then
             return
         fi
-        java "$package_name.$main_file" && remove_compiled_files directory
+        { java "$package_name.$main_file" && remove_compiled_files directory; } || rm ".timestamp"
     else
-        stderr="$(javac "${main_file}.java" 2>&1 > /dev/null)"
-        if [[ "$stderr" =~ "Usage" ]]; then
-            echo "$stderr" | sed -z --expression='s/javac/jr/; s:<:[:; s:>:]:' # change to match help
-            exit 1;
-        fi
-
-        # TODO - javac can be skipped, speeding `jr -d` up
-        # FIXME - running jr is very slow if it isn't already compiled (almost twice the duration)
         if [[ ! -f ".timestamp" ]] || [[ ".timestamp" -ot "${main_file}.java" ]]; then
             touch ".timestamp"
-            { javac "${main_file}.java" && java "${main_file}" && remove_compiled_files file; } || rm ".timestamp"
+            compile_test "single"
+        fi
+        if (( $? != 0 )); then
+            touch -m "${main_file}.java" # is there a more efficient way to do this
             return
         fi
-        java "${main_file}" && remove_compiled_files file
+        { java "${main_file}" && remove_compiled_files file; } || rm ".timestamp"
     fi
 }
 
@@ -177,6 +181,7 @@ test_files() {
     javac -d . -cp "$jarname" *.java
     java -jar "$jarname" -cp . --scan-class-path | less -r # pipe result with color into pager
 
+    # FIXME - first `jr` after `jr -t` fails
     rm -r "$package_name"
 }
 
